# Generated by Django 4.0.1 on 2022-01-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_art',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
