# Generated by Django 4.0.1 on 2022-01-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_album_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_art',
            field=models.FileField(null=True, upload_to='static/album_artwork'),
        ),
    ]
