# Generated by Django 4.0.1 on 2022-01-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_song_album_art'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album_art',
        ),
        migrations.AddField(
            model_name='song',
            name='album_art_link',
            field=models.TextField(null=True),
        ),
    ]
